### PR TITLE
Only remove remote name on branch name parsing

### PR DESCRIPTION
**Pull request by inkel**
Branch names can contain `/` characters, and rotten was stripping everything that was preceded by a `/` in the branch name. This wrongly parses a branch like `origin/feature/123-lorem-ipsum` into `123-lorem-ipsum`, which is wrong.

### CODE REVIEW

**Comment by DTrejo** [comment]
Thanks for the pullreq!

Will merge & test & publish this weekend I hope!

**Comment by inkel** [comment]
My pleasure! Let me know if you have any issues with it :)

**Comment by DTrejo** [comment]
taken in f3709ea43af7caaa95e8a61b1a69885d4a2c5738 Thank you!
D

**Comment by inkel** [comment]
My pleasure! Glad to be of help :)

**Pull request closed without merging**
